const images = {
  logo: "/assets/logo.svg",
  ctf: "/assets/capture-the-flag.png",
  profile: "/assets/profile.jpg",
  circle: "/assets/circle.svg",
  projecthorizon: "/assets/projecthorizon.png",
  sudoku: "/assets/sudoku.png",
  circle1: "/assets/circles/circle1.svg",
  circle2: "/assets/circles/circle2.svg",
  circle3: "/assets/circles/circle3.svg",
  circle4: "/assets/circles/circle4.svg",
  circle5: "/assets/circles/circle5.svg",
  chess: "/assets/chess.png",
  cars: "/assets/cars.png",
  twitter: "/assets/twitter.png",
  amnews: "/assets/amnews.png",
  flappy: "/assets/flappy.png",
  amtimer: "/assets/amtimer.png",
  shooter: "/assets/shooter.png",
  portals: "/assets/portals.png",
  cubeSolver: "/assets/cube-solver.png",
  compiler: "/assets/compiler.png",
  glove: "/assets/glove.JPEG",
  robot: "/assets/robot.JPEG",
  chip: "/assets/chip.png",
  aws: "/assets/aws.png",
  notreDame: "/assets/notre-dame.png",
  jpl: "/assets/jpl.png",
  fountainBowl: "/assets/fountain-bowl.png",
};

export default images;
